[en]
  title = "ZDoc"
  languageName = "English"
  weight = 1
  contentdir = "content/en"

[zh-CN]
  title = "ZDoc"
  languageName = "简体中文"
  weight = 2
  contentdir = "content/zh-cn"

[ko]
  title = "ZDoc"
  languageName = "한국어"
  weight = 2
  contentdir = "content/ko"
